version: '3.1'

services:

  wordpress:
    volumes:
      - ./wordpress:/var/www/html

  cli:
    image: wordpress:cli
    volumes:
      - ./wordpress:/var/www/html

  wordpress_e2e_tests:
    volumes:
      - ./wordpress:/var/www/html

  cli_e2e_tests:
    volumes:
      - ./wordpress:/var/www/html
