version: '3.1'

services:

  wordpress:
    volumes:
      - ./wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/gutenberg
      - ./test/e2e/test-plugins:/var/www/html/wp-content/plugins/gutenberg-test-plugins
      - ./test/e2e/test-mu-plugins:/var/www/html/wp-content/mu-plugins

  cli:
    image: wordpress:cli
    volumes:
      - ./wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/gutenberg

  wordpress_e2e_tests:
    volumes:
      - ./wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/gutenberg
      - ./test/e2e/test-plugins:/var/www/html/wp-content/plugins/gutenberg-test-plugins
      - ./test/e2e/test-mu-plugins:/var/www/html/wp-content/mu-plugins

  cli_e2e_tests:
    volumes:
      - ./wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/gutenberg
