name: Bug report
description: Report a bug with the WordPress block editor or Gutenberg plugin
title: '<title>'
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report! If this is a security issue, please report it in HackerOne instead: https://hackerone.com/wordpress
    - type: textarea
      attributes:
          label: Description ands step-by-step reproduction instructions
          description: Please write a brief description of the bug and the steps needed to reproduce it.
          placeholder: |
              1. Go to '...'
              2. Click on '...'
              3. Scroll down to '...'
              4. See error...
      validations:
          required: true

    - type: textarea
      attributes:
          label: Expected vs Current Behavior
          description: Please describe what you expected to happen and what you are actually experiencing.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots, screen recording, code snippet (optional)
          description: |
              If possible, please upload a screenshot or screen recording which demonstrates the bug. You can use LIEcap to create a GIF screen recording: https://www.cockos.com/licecap/
              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
              If this bug is to related to a developer API, please share a code snippet that demonstrates the issue. For small snippets paste it directly here, or you can use GitHub Gist to share multiple code files: https://gist.github.com
              Please ensure the shared code can be used by a developer to reproduce the issue—ideally it can be copied into a local development environment or executed in a browser console to help debug the issue
      validations:
          required: false

    - type: textarea
      attributes:
          label: Environment info
          description: |
              Please list what Gutenberg version you are using. If you aren't using Gutenberg, please note that it's not installed.
          placeholder: |
            - WordPress version, Gutenberg version.
            - Browser(s) are you seeing the problem on.
            - Device you are using and operating system (e.g. "Desktop with Windows 10", "iPhone with iOS 14", etc.)
      validations:
          required: false
          
    - type: checkboxes
      attributes:
          label: Prechecks
          description: Please check if the bug has already been reported by searching https://github.com/WordPress/gutenberg/issues and make sure before reporting the bug is neither related to another plugin nor theme specific.
          options:
              - label: I have searched the existing issues.
                required: true
              - label: I have tested with all plugins deactivated except Gutenberg.
                required: true
              - label: I have tested with a default theme.
                required: true
