name: Verify @wordpress/components CHANGELOG update

on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'packages/components/**'
            - '!packages/components/src/**/stories/**'
            - '!packages/components/src**/test/**'
jobs:
    check:
        name: Check CHANGELOG diff
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
            - name: Run git diff
              run: |
                  changelog_path="packages/components/CHANGELOG.md"
                  if git diff --quiet ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- "$changelog_path"; then
                    echo "Please add a CHANGELOG entry to $changelog_path"
                    exit 1
                  fi
