name: Verify Core Backport Changlog

on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'lib/**'
            - '!lib/experimental/**'
            - 'packages/**/*.php'
            - 'phpunit/**'
jobs:
    check:
        name: Check CHANGELOG diff
        runs-on: ubuntu-latest
        steps:
            - name: 'Get PR commit count'
              run: echo "PR_COMMIT_COUNT=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"
            - name: Checkout code
              uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  fetch-depth: ${{ env.PR_COMMIT_COUNT }}
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
            - name: 'Fetch relevant history from origin'
              run: git fetch origin ${{ github.event.pull_request.base.ref }}
            - name: Check CHANGELOG status
              env:
                  PR_NUMBER: ${{ github.event.number }}
              run: |
                  changelog_folder="backport-changelog"

                  # Fail if the PR doesn't touch the changelog
                  if git diff --quiet ${{ github.event.pull_request.base.sha }} HEAD -- "$changelog_folder"; then
                    echo "Please create a file with the name ${PR_NUMBER}.md in the $changelog_folder folder with the core backport PR URL as content."
                    echo "If changes are related to an existing, open core PR, you may use that PR."
                    exit 1
                  fi

                  changelog_file=$(find "${changelog_folder}" -type f -name "${PR_NUMBER}.md" | head -n 1)

                  # Confirm that there is an entry.
                  if [[ -z "${changelog_file}" ]]; then
                    echo "Please create a file with the name ${PR_NUMBER}.md in the $changelog_folder folder with the core backport PR URL as content."
                    echo "If changes are related to an existing, open core PR, you may use that PR."
                    exit 1
                  fi

                  pr_link_grep_pattern="https://github\.com/WordPress/wordpress-develop/pull/\([0-9]\+\)"

                  # Confirm that the entry has a core backport PR URL.
                  if ! grep -nq -e "${pr_link_grep_pattern}" "${changelog_file}"; then
                    echo "Please add a CORE PR URL to $changelog_file."
                    echo "If changes are related to an existing, open core PR, you may use that PR."
                    exit 1
                  fi
