name: Create Playground Link

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/changelog/**'
      - '**/tests/**'
      - '**/*.md'

jobs:
  create-playground-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # We need to wait for the release artifcat to be created and uploaded
      # before creating the URL for the playground, as the playground relies
      # on the artifact, which is the actual plugin zip it ends up installing.
      - name: Wait for Build Gutenberg Plugin Zip workflow
        uses: kamilchodola/wait-for-workflow-action@1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: 'build-plugin-zip.yml'
          max_wait_minutes: '3'
          interval: '5'
          timeout: '60'
          org_name: 'fullofcaffeine' # @todo change this
          repo_name: 'gutenberg' # @odo change this
          ref: '${{ github.ref }}'

      - name: Create WordPress Playground link comment
        uses: actions/github-script@v7
        with:
          script: |
            const { run } = require('./.github/workflows/scripts/generate-playground-blueprint.js');
            run({ github, context });
