name: 'Validate Gradle Wrapper'
on: [push, pull_request]

jobs:
    validation:
        name: 'Validation'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
            - uses: gradle/wrapper-validation-action@v3
