name: 'Validate Gradle Wrapper'
on: [push, pull_request]

jobs:
    validation:
        name: 'Validation'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
            - uses: gradle/wrapper-validation-action@v1
