name: 'Validate Gradle Wrapper'
on: [push, pull_request]

jobs:
    validation:
        name: 'Validation'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
            - uses: gradle/wrapper-validation-action@v3
