name: Performance Tests

on:
    pull_request:
    release:
        types: [published]
    push:
        branches: [trunk]
    workflow_dispatch:
        inputs:
            branches:
                description: 'branches or commits to compare (comma separated)'
                required: true
            wpversion:
                description: 'The base WP version to use for the tests (latest or 6.0, 6.1...)'
                required: false
                default: 'latest'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    performance:
        name: Run performance tests
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' }}
        env:
            WP_ARTIFACTS_PATH: ${{ github.workspace }}/artifacts

        steps:
            - run: echo hello
