name: PHPUnit Tests

# Since Unit Tests are required to pass for each PR,
# we cannot disable them for documentation-only changes.
on:
    pull_request:
    push:
        branches:
            - trunk
            - 'release/**'
            - 'wp/**'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    test-php:
        name: ${{ matrix.php }}${{ matrix.multisite && ' multisite' || '' }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        timeout-minutes: 20
        if: ${{ github.repository == 'WordPress/gutenberg' || github.event_name == 'pull_request' }}
        strategy:
            fail-fast: false
            matrix:
                php:
                    [
                        '5.6',
                        '7.0',
                        '7.1',
                        '7.2',
                        '7.3',
                        '7.4',
                        '8.0',
                        '8.1',
                        '8.2',
                    ]
                os: [ubuntu-latest]
                multisite: [false, true]

        env:
            WP_ENV_PHP_VERSION: ${{ matrix.php }}

        steps:
            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

            - name: Set up Node.js
              uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            ##
            # This allows Composer dependencies to be installed using a single step.
            #
            # Since the tests are currently run within the Docker containers where the PHP version varies,
            # the same PHP version needs to be configured for the action runner machine so that the correct
            # dependency versions are installed and cached.
            ##
            - name: Set up PHP
              uses: shivammathur/setup-php@1a18b2267f80291a81ca1d33e7c851fe09e7dfc4 # v2.22.0
              with:
                  php-version: '${{ matrix.php }}'
                  coverage: none

            # Since Composer dependencies are installed using `composer update` and no lock file is in version control,
            # passing a custom cache suffix ensures that the cache is flushed at least once per week.
            - name: Install Composer dependencies
              uses: ramsey/composer-install@83af392bf5f031813d25e6fe4cd626cdba9a2df6 # v2.2.0
              with:
                  custom-cache-suffix: $(/bin/date -u --date='last Mon' "+%F")

            - name: Install npm dependencies
              run: |
                  npm ci
                  npm run build

            - name: Docker debug information
              run: |
                  docker -v
                  docker-compose -v

            - name: General debug information
              run: |
                  npm --version
                  node --version
                  curl --version
                  git --version
                  svn --version
                  composer --version
                  locale -a

            - name: Start Docker environment
              run: |
                  npm run wp-env start

            - name: Log running Docker containers
              run: docker ps -a

            - name: Docker container debug information
              run: |
                  npm run wp-env run tests-mysql "mysql --version"
                  npm run wp-env run phpunit "php --version"
                  npm run wp-env run phpunit "php -m"
                  npm run wp-env run phpunit "php -i"
                  npm run wp-env run phpunit "/usr/local/bin/phpunit --version"
                  npm run wp-env run phpunit "locale -a"

            - name: Running single site unit tests
              run: npm run wp-env run phpunit "/usr/local/bin/phpunit -c /var/www/html/wp-content/plugins/gutenberg/phpunit.xml.dist --verbose"
              if: ${{ ! matrix.multisite }}

            - name: Running multisite unit tests
              run: npm run wp-env run phpunit "/usr/local/bin/phpunit -c /var/www/html/wp-content/plugins/gutenberg/multisite.xml.dist --verbose"
              if: ${{ matrix.multisite }}
