on: pull_request
name: Pull request automation

jobs:
  pull-request-automation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: cd packages/project-management-automation && npm install
      - uses: ./packages/project-management-automation
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
