on:
  pull_request_target:
    types: [opened]
  push:
name: Pull request automation

jobs:
  pull-request-automation:
    runs-on: ubuntu-latest
    steps:
    # Checkout defaults to using the branch which triggered the event, which
    # isn't necessarily `master` (e.g. in the case of a merge).
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    # Changing into the action's directory and running `npm install` is much
    # faster than a full project-wide `npm ci`.
    - run: cd packages/project-management-automation && npm install

    - uses: ./packages/project-management-automation
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
