name: React Native E2E Tests (iOS)

on:
  pull_request:
    paths-ignore:
    - '**.md'
  push:
    branches: [master]
    paths-ignore:
    - '**.md'

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        native-test-name: [
          gutenberg-editor-gallery
        ]

    steps:
    - uses: actions/checkout@v2

    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}


    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

