name: 'Mark issues stale that require info'
on:
    schedule:
        - cron: '30 1 * * *'

permissions:
  contents: read

jobs:
    stale:
        permissions:
          issues: write  # for actions/stale to close stale issues
          pull-requests: write  # for actions/stale to close stale PRs
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' }}

        steps:
            - uses: actions/stale@996798eb71ef485dc4c7b4d3285842d714040c4a # v3.0.17
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  stale-issue-message: 'Help us move this issue forward. This issue is being marked stale since it has no activity after 15 days of requesting more information. Please add info requested so we can help move the issue forward. Note: The triage policy is to close stale issues that need more info and no response after 2 weeks.'
                  days-before-stale: 15
                  days-before-close: -1
                  only-labels: '[Status] Needs More Info'
                  stale-issue-label: '[Status] Stale'
