name: "Close stale issues that requires info"
on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is being marked as stale because it is marked "Needs More Info" and has been 15 days with no activity. To keep open, remove the stale label or comment on the issue, else this will be closed in 5 days.'
        close-issue-message: 'This issue was closed because more information was requested and there was no activity. If this is a bug report and still a problem, please supply the additional information requested and reopen the issue.'
        days-before-stale: 15
        days-before-close: 5
        only-labels: '[Status] Needs More Info'
        stale-issue-label: '[Status] Stale'
