name: Static Analysis (Linting, License, Type checks...)

on:
    pull_request:
    push:
        branches:
            - trunk
            - 'release/**'
            - 'wp/**'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    test-npm-publish:
        name: Publish WordPress packages to npm (Work In Progress)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout (for CLI)
              uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
              with:
                  path: main

            - name: Checkout (for publishing)
              uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
              with:
                  path: publish
                  ref: trunk
                  token: ${{ secrets.GUTENBERG_TOKEN }}

            - name: Configure git user name and email (for publishing)
              run: |
                  cd publish
                  git config user.name "Gutenberg Repository Automation"
                  git config user.email gutenberg@wordpress.org

            - name: Setup Node
              uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f # v2.2.2
              with:
                  node-version: 14
                  registry-url: 'https://registry.npmjs.org'

            - name: Publish packages to npm
              run: |
                  cd main
                  npm ci
                  ./bin/plugin/cli.js npm-next --ci --repository-path ../publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    check:
        name: All
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' || github.event_name == 'pull_request' }}

        steps:
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

            - name: Use desired version of NodeJS
              uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f # v2.2.2
              with:
                  node-version: 14
                  cache: npm

            - name: Npm install
              # A "full" install is executed, since `npm ci` does not always exit
              # with an error status code if the lock file is inaccurate.
              #
              # See: https://github.com/WordPress/gutenberg/issues/16157
              run: npm install

            - name: Lint JavaScript and Styles
              run: npm run lint

            - name: Type checking
              run: npm run build:package-types

            - name: Check local changes
              run: npm run check-local-changes

            - name: License compatibility
              run: npm run check-licenses
