name: Static Analysis (Linting, License, Type checks...)

on:
    pull_request:
    push:
        branches:
            - trunk
            - 'release/**'
            - 'wp/**'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    build-artifacts:
        name: Check for build artifacts
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

            - name: Use Node.js 14.x
              uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # v2.1.5
              with:
                  node-version: 14.x

            - name: Cache NPM packages
              uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

            - name: Install NPM packages
              run: npm install

            - name: Build the project
              run: npm run build

            - name: Build artifacts
              run: npm run check-local-changes

    prepare:
        name: Prepare for analysis
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

            - name: Use Node.js 14.x
              uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # v2.1.5
              with:
                  node-version: 14.x

            - name: Cache node modules
              uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

            - name: Npm install and build
              # A "full" install is executed, since `npm ci` does not always exit
              # with an error status code if the lock file is inaccurate.
              #
              # See: https://github.com/WordPress/gutenberg/issues/16157
              run: |
                  npm install
                  npm run build

            - uses: actions/upload-artifact@v2
              with:
                  name: ${{ github.sha }}
                  path: |
                      ${{ github.workspace }}
                      !**node_modules

    check-for-artifacts:
        name: Check for build artifacts
        runs-on: ubuntu-latest
        needs: prepare

        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: ${{ github.sha }}

            - name: Use Node.js 14.x
              uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # v2.1.5
              with:
                  node-version: 14.x

            - name: Cache node modules
              uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

            - name: Npm install and build
              # A "full" install is executed, since `npm ci` does not always exit
              # with an error status code if the lock file is inaccurate.
              #
              # See: https://github.com/WordPress/gutenberg/issues/16157
              run: |
                  npm install

            - name: Build artifacts
              run: npm run check-local-changes

    lint:
        name: Linting
        runs-on: ubuntu-latest
        needs: check-for-artifacts

        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: ${{ github.sha }}

            - name: Use Node.js 14.x
              uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # v2.1.5
              with:
                  node-version: 14.x

            - name: Cache node modules
              uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

            - name: Npm install and build
              # A "full" install is executed, since `npm ci` does not always exit
              # with an error status code if the lock file is inaccurate.
              #
              # See: https://github.com/WordPress/gutenberg/issues/16157
              run: |
                  npm ci

            - name: Lint JavaScript and Styles
              run: npm run lint

    type-checking:
        name: Type checking
        runs-on: ubuntu-latest
        needs: check-for-artifacts

        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: ${{ github.sha }}

            - name: Use Node.js 14.x
              uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # v2.1.5
              with:
                  node-version: 14.x

            - name: Cache node modules
              uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

            - name: Npm install and build
              # A "full" install is executed, since `npm ci` does not always exit
              # with an error status code if the lock file is inaccurate.
              #
              # See: https://github.com/WordPress/gutenberg/issues/16157
              run: |
                  npm ci

            - name: Type checking
              run: npm run build:package-types

    license-checks:
        name: License checks
        runs-on: ubuntu-latest
        needs: check-for-artifacts

        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: ${{ github.sha }}

            - name: Use Node.js 14.x
              uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # v2.1.5
              with:
                  node-version: 14.x

            - name: Cache node modules
              uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

            - name: Npm install and build
              run: |
                  npm ci

            - name: License compatibility
              run: npm run check-licenses

    check:
        name: All

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

            - name: Use Node.js 14.x
              uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # v2.1.5
              with:
                  node-version: 14.x

            - name: Cache node modules
              uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

            - name: Npm install and build
              # A "full" install is executed, since `npm ci` does not always exit
              # with an error status code if the lock file is inaccurate.
              #
              # See: https://github.com/WordPress/gutenberg/issues/16157
              run: |
                  npm install
                  npm run build

            - name: Lint JavaScript and Styles
              run: npm run lint

            - name: Type checking
              run: npm run build:package-types

            - name: Build artifacts
              run: npm run check-local-changes

            - name: License compatibility
              run: npm run check-licenses
