on:
  release:
    types: [released]

name: Upload Gutenberg plugin to WordPress.org plugin repo

jobs:
  upload:
    name: Upload Gutenberg Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Check out Gutenberg trunk from WP.org plugin repo
        env:
          PLUGIN_REPO_URL: 'https://plugins.svn.wordpress.org/gutenberg'
        run: svn checkout "$PLUGIN_REPO_URL/trunk"

      - name: Delete everything
        run: find ./trunk -maxdepth 1 -not -name ".svn" -not -name "." -not -name ".." -exec rm -rf {} +

      - name: Download and unzip Gutenberg plugin asset
        env:
          PLUGIN_URL: ${{ github.event.release.assets[0].browser_download_url }}
        run: |
          curl -L -o gutenberg.zip $PLUGIN_URL
          unzip gutenberg.zip -d gutenberg
          rm gutenberg.zip
